#pragma once
#include <cell\sysmodule.h>
#include <cell/cell_fs.h>
#include <cell/pad/libpad.h>
#include <initializer_list>
#include <ppu_intrinsics.h>
#include <stdarg.h>
#include <string>
#include <sys/memory.h>
#include <sys/sys_time.h>
#include <sys/ppu_thread.h>
#include <sys/process.h>
#include <sys/prx.h>
#include <sys/syscall.h>
#include <sys/timer.h>
#include <algorithm>
#include <float.h>
#include <math.h>
#include <fastmath.h>
#include <libpsutil.h>
#include <vector>
#include <map>
#include <stack>
#include <csetjmp>
#include <np.h>
#include <cell/http.h>
#include <sys/synchronization.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <netex\libnetctl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <cstring>
#include <cell\mstream.h>
#include <semaphore.h>
#include <pthread.h>
#include <sched.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <sysutil/sysutil_msgdialog.h>
#include <sysutil/sysutil_oskdialog.h>
#include <sysutil/sysutil_userinfo.h>
//#include <PowerObfuscator.h>
#include <cstdlib>
#include <cell/pad.h>
#include <cell/pad/pad_codes.h>
#include <cell/error.h>
#include <functional>

// projeto include trash
#include <stdint.h>
#include "utils/Dialog.h"
#include "utils/enum.h"
#include "rage/Natives.h"
#include "utils/variables.h"
#include "mods/mods.h"
#include "mods/stats/stats.h"
#include "mods/protection/protection.h"
#include "mods/freeze/freeze.h"
#include "mods/weather/weather.h"
#include "mods/teleport/teleport.h"
#include "tests.h"
#include "menu/menu.h"